// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfliEAaa91ijPV0Jc3YSQXNr_Y8kODG7I',
    appId: '1:97473591547:web:e3ab5cadaa3ba9267d585e',
    messagingSenderId: '97473591547',
    projectId: 'stitchcraft-e62da',
    authDomain: 'stitchcraft-e62da.firebaseapp.com',
    storageBucket: 'stitchcraft-e62da.firebasestorage.app',
    measurementId: 'G-S90MLYLX3T',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_kp5MfG_nIv62W45ji8L_fJ63dBG4qT8',
    appId: '1:97473591547:android:ab382ad9ab8fa9f37d585e',
    messagingSenderId: '97473591547',
    projectId: 'stitchcraft-e62da',
    storageBucket: 'stitchcraft-e62da.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBowQT-bgcTQVyN1MelAMVaifePTiT8yzw',
    appId: '1:97473591547:ios:ee06f7edbe111c207d585e',
    messagingSenderId: '97473591547',
    projectId: 'stitchcraft-e62da',
    storageBucket: 'stitchcraft-e62da.firebasestorage.app',
    iosClientId: '97473591547-q9hes88dabujoql4hflk556a9trr8ps0.apps.googleusercontent.com',
    iosBundleId: 'com.example.stitchcraft',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBowQT-bgcTQVyN1MelAMVaifePTiT8yzw',
    appId: '1:97473591547:ios:ee06f7edbe111c207d585e',
    messagingSenderId: '97473591547',
    projectId: 'stitchcraft-e62da',
    storageBucket: 'stitchcraft-e62da.firebasestorage.app',
    iosClientId: '97473591547-q9hes88dabujoql4hflk556a9trr8ps0.apps.googleusercontent.com',
    iosBundleId: 'com.example.stitchcraft',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDfliEAaa91ijPV0Jc3YSQXNr_Y8kODG7I',
    appId: '1:97473591547:web:73f29369137b50207d585e',
    messagingSenderId: '97473591547',
    projectId: 'stitchcraft-e62da',
    authDomain: 'stitchcraft-e62da.firebaseapp.com',
    storageBucket: 'stitchcraft-e62da.firebasestorage.app',
    measurementId: 'G-71G8TTGD3K',
  );

}
